In [1]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn import preprocessing
from sklearn.metrics import f1_score
from sklearn.impute import SimpleImputer

In [2]:
data_test=pd.read_csv(r"C:\Users\sarva\Desktop\Avishkar 2020\Logical Rythm\Tow-Mater Labs\test.csv")


In [3]:
data_train=pd.read_csv("train.csv")

In [4]:
data_train.head()
X = data_train[['id','blood_group','Gender','Age','Driving_License','Region_Code','Previously_Insured','Vehicle_Age','Vehicle_Damage','Annual_Premium','Policy_Sales_Channel','Vintage','mother_age','father_age']].values
Y = data_train["accepted"].values
X1= data_test[['id','blood_group','Gender','Age','Driving_License','Region_Code','Previously_Insured','Vehicle_Age','Vehicle_Damage','Annual_Premium','Policy_Sales_Channel','Vintage','mother_age','father_age']].values

In [5]:
from sklearn import preprocessing
le_sex = preprocessing.LabelEncoder()
le_sex.fit(['Female','Male'])
X1[:,2] = le_sex.transform(X1[:,2]) 


le_BP = preprocessing.LabelEncoder()
le_BP.fit([ 'O', 'AB+', 'AB-','A+','A-','B+','B-'])
X1[:,1] = le_BP.transform(X1[:,1])


le_Chol = preprocessing.LabelEncoder()
le_Chol.fit([ '< 1 Year','1-2 Year','> 2 Years'])
X1[:,7] = le_Chol.transform(X1[:,7])

vd=preprocessing.LabelEncoder()
vd.fit(['Yes','No'])
X1[:,8]=vd.transform(X1[:,8])

X1[0:5]

array([[485035, 4, 0, 21, 1, 8.0, 0, 0, 1, 43500.0, 157.0, 266, 64, 62],
       [278306, 6, 1, 53, 1, 2.0, 0, 0, 1, 33547.0, 26.0, 119, 76, 79],
       [478061, 2, 0, 23, 1, 30.0, 1, 1, 0, 41650.0, 152.0, 84, 61, 77],
       [109822, 3, 0, 46, 1, 28.0, 0, 0, 1, 39209.0, 37.0, 299, 70, 70],
       [272343, 3, 0, 30, 1, 28.0, 0, 0, 1, 43252.0, 26.0, 215, 73, 62]],
      dtype=object)

In [6]:
from sklearn import preprocessing
le_sex = preprocessing.LabelEncoder()
le_sex.fit(['Female','Male'])
X[:,2] = le_sex.transform(X[:,2]) 


le_BP = preprocessing.LabelEncoder()
le_BP.fit([ 'O', 'AB+', 'AB-','A+','A-','B+','B-'])
X[:,1] = le_BP.transform(X[:,1])


le_Chol = preprocessing.LabelEncoder()
le_Chol.fit([ '< 1 Year','1-2 Year','> 2 Years'])
X[:,7] = le_Chol.transform(X[:,7])

vd=preprocessing.LabelEncoder()
vd.fit(['Yes','No'])
X[:,8]=vd.transform(X[:,8])

X[0:5]

array([[223723, 6, 0, 23, 1, 18.0, 1, 1, 0, 29223.0, 152.0, 89, 70, 65],
       [102674, 3, 1, 44, 1, 23.0, 0, 0, 1, 28501.0, 26.0, 111, 61, 66],
       [15567, 2, 1, 23, 1, 41.0, 0, 1, 1, 32590.0, 152.0, 71, 67, 78],
       [222937, 6, 1, 78, 1, 15.0, 1, 0, 0, 2630.0, 14.0, 245, 74, 63],
       [32565, 4, 0, 25, 1, 44.0, 1, 1, 0, 31821.0, 152.0, 59, 73, 62]],
      dtype=object)

In [7]:
#Modelling
output=pd.read_csv("sample.csv")
x_id=o["id"].values

In [8]:
#PreProcessing
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))
X[0:5]

array([[-0.18307922,  1.52212748, -1.08716659, -1.02159651,  0.04578238,
        -0.63507239,  1.08930298,  0.8389457 , -1.01147617, -0.07728183,
         0.7382359 , -0.78012877,  0.08462366, -0.78132148],
       [-1.02109473, -0.50468802,  0.91982223,  0.33174101,  0.04578238,
        -0.25706013, -0.91801823, -0.89211507,  0.98865404, -0.11927168,
        -1.58551343, -0.51738554, -1.47491684, -0.60795717],
       [-1.62413166, -1.18029319,  0.91982223, -1.02159651,  0.04578238,
         1.10378402, -0.91801823,  0.8389457 ,  0.98865404,  0.11853514,
         0.7382359 , -0.99510051, -0.43522317,  1.47241458],
       [-0.18852065,  1.52212748,  0.91982223,  2.5228589 ,  0.04578238,
        -0.86187975,  1.08930298, -0.89211507, -1.01147617, -1.62386945,
        -1.80682289,  1.08295962,  0.77775277, -1.12805011],
       [-1.50645545,  0.17091715, -1.08716659, -0.89270722,  0.04578238,
         1.33059137,  1.08930298,  0.8389457 , -1.01147617,  0.07381187,
         0.7382359 , -1.13

In [12]:
#KNN Algorithm
from sklearn.neighbors import KNeighborsClassifier
k = 4
#Train Model and Predict  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X,Y)
neigh

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                     weights='uniform')

In [13]:
yhat = neigh.predict(X1)
yhat[0:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [14]:
df=pd.DataFrame({'id':x_id,'accepted':yhat})
df=df.astype(int)
df.to_csv('Submission3.csv',index=False)